name: Lint

on:
  push:
    paths:
      - "**.py"
      - "requirements*.txt"
  pull_request:
    paths:
      - "**.py"
      - "requirements*.txt"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - uses: astral-sh/ruff-action@v3
        with:
          src: "./geni"
