name: Build and Publish to testPyPI

on:
  push:
    paths:
      - 'geni/version.py'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: pip
          cache-dependency-path: requirements*.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-pkg.txt

      - name: Build package
        run: |
          python -m build

      - name: Upload to PyPI
        env:
          PYPI_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: |
          twine upload --repository testpypi dist/*
